# -*- mode: python -*-

Import("env")

decimalKnobsEnv = env.Clone()

if GetOption('enable-experimental-decimal-support') == 'on':
    decimalKnobsEnv.Append(
        CPPDEFINES = {
            "ENABLE_EXPERIMENTAL_DECIMAL_SUPPORT" : 1
        }
    )

decimalKnobsEnv.Library(
	target='decimal_knobs',
	source=[
        'decimal128_knobs.cpp',
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/server_parameters",
    ])

Export('decimalKnobsEnv')

env.Library('platform', [
        'decimal128.cpp',
        'posix_fadvise.cpp',
        'process_id.cpp',
        'random.cpp',
        "shared_library.cpp",
        "shared_library_${TARGET_OS_FAMILY}.cpp",
        'strcasestr.cpp',
        ],
        LIBDEPS=['$BUILD_DIR/third_party/shim_intel_decimal128'])

env.CppUnitTest('atomic_word_test', 'atomic_word_test.cpp')
env.CppUnitTest('bits_test', 'bits_test.cpp')
env.CppUnitTest('endian_test', 'endian_test.cpp')
env.CppUnitTest('process_id_test', 'process_id_test.cpp', LIBDEPS=['platform'])
env.CppUnitTest('random_test', 'random_test.cpp', LIBDEPS=['platform'])
env.CppUnitTest('decimal128_test', 'decimal128_test.cpp', LIBDEPS=['platform']);